/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/FemaleEngineer.glb -o src/components/FemaleEngineer.jsx -r public 
*/

import React from "react";

export function FemaleEngineer(
  nodes,
  materials,
  hairColor,
  topColor,
  bottomColor
) {
  return (
    <group name="Root_Scene">
      <group name="RootNode">
        <group
          name="CharacterArmature"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <primitive object={nodes.Root} />
        </group>
        <group name="Worker_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Worker_Body_1"
            geometry={nodes.Worker_Body_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Worker_Body_1.skeleton}
          />
          <skinnedMesh
            name="Worker_Body_2"
            geometry={nodes.Worker_Body_2.geometry}
            material={materials.Worker_Vest}
            skeleton={nodes.Worker_Body_2.skeleton}
          >
            <meshStandardMaterial color={topColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Worker_Body_3"
            geometry={nodes.Worker_Body_3.geometry}
            material={materials.Worker_Yellow}
            skeleton={nodes.Worker_Body_3.skeleton}
          />
          <skinnedMesh
            name="Worker_Body_4"
            geometry={nodes.Worker_Body_4.geometry}
            material={materials.White}
            skeleton={nodes.Worker_Body_4.skeleton}
          />
        </group>
        <group name="Worker_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Worker_Feet_1"
            geometry={nodes.Worker_Feet_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Worker_Feet_1.skeleton}
          />
          <skinnedMesh
            name="Worker_Feet_2"
            geometry={nodes.Worker_Feet_2.geometry}
            material={materials.Black}
            skeleton={nodes.Worker_Feet_2.skeleton}
          />
        </group>
        <group name="Worker_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Worker_Head_1"
            geometry={nodes.Worker_Head_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Worker_Head_1.skeleton}
          />
          <skinnedMesh
            name="Worker_Head_2"
            geometry={nodes.Worker_Head_2.geometry}
            material={materials.Worker_Yellow}
            skeleton={nodes.Worker_Head_2.skeleton}
          >
            <meshStandardMaterial color={hairColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Worker_Head_3"
            geometry={nodes.Worker_Head_3.geometry}
            material={materials.DarkBrown}
            skeleton={nodes.Worker_Head_3.skeleton}
          />
          <skinnedMesh
            name="Worker_Head_4"
            geometry={nodes.Worker_Head_4.geometry}
            material={materials.Brown}
            skeleton={nodes.Worker_Head_4.skeleton}
          />
        </group>
        <group name="Worker_Legs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Worker_Legs_1"
            geometry={nodes.Worker_Legs_1.geometry}
            material={materials.Brown_02}
            skeleton={nodes.Worker_Legs_1.skeleton}
          >
            <meshStandardMaterial color={bottomColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Worker_Legs_2"
            geometry={nodes.Worker_Legs_2.geometry}
            material={materials.Brown2}
            skeleton={nodes.Worker_Legs_2.skeleton}
          >
            <meshStandardMaterial color={bottomColor} />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
}
