/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/FemaleCasual.glb -o src/components/FemaleCasual.jsx -r public 
*/

import React from "react";

export function FemaleCasual(
  nodes,
  materials,
  hairColor,
  topColor,
  bottomColor
) {
  return (
    <group name="Root_Scene">
      <group name="RootNode">
        <group
          name="CharacterArmature"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <primitive object={nodes.Root} />
        </group>
        <group name="Formad_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Formad_Head_1"
            geometry={nodes.Formad_Head_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Formad_Head_1.skeleton}
          />
          <skinnedMesh
            name="Formad_Head_2"
            geometry={nodes.Formad_Head_2.geometry}
            material={materials.Red}
            skeleton={nodes.Formad_Head_2.skeleton}
          >
            <meshStandardMaterial color={hairColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Formad_Head_3"
            geometry={nodes.Formad_Head_3.geometry}
            material={materials.Brown}
            skeleton={nodes.Formad_Head_3.skeleton}
          />
        </group>
        <group name="Formal_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Formal_Body_1"
            geometry={nodes.Formal_Body_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Formal_Body_1.skeleton}
          />
          <skinnedMesh
            name="Formal_Body_2"
            geometry={nodes.Formal_Body_2.geometry}
            material={materials.LimeGreen}
            skeleton={nodes.Formal_Body_2.skeleton}
          >
            <meshStandardMaterial color={topColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Formal_Body_3"
            geometry={nodes.Formal_Body_3.geometry}
            material={materials.Gold}
            skeleton={nodes.Formal_Body_3.skeleton}
          />
        </group>
        <group name="Formal_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Formal_Feet_1"
            geometry={nodes.Formal_Feet_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Formal_Feet_1.skeleton}
          />
          <skinnedMesh
            name="Formal_Feet_2"
            geometry={nodes.Formal_Feet_2.geometry}
            material={materials.Red}
            skeleton={nodes.Formal_Feet_2.skeleton}
          />
        </group>
        <group name="Formal_Legs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Formal_Legs_1"
            geometry={nodes.Formal_Legs_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Formal_Legs_1.skeleton}
          >
            <meshStandardMaterial color={bottomColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Formal_Legs_2"
            geometry={nodes.Formal_Legs_2.geometry}
            material={materials.LimeGreen}
            skeleton={nodes.Formal_Legs_2.skeleton}
          >
            <meshStandardMaterial color={topColor} />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
}
