/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/FemaleSoldier.glb -o src/components/FemaleSoldier.jsx -r public 
*/

import React from "react";

export function FemaleSoldier(
  nodes,
  materials,
  hairColor,
  topColor,
  bottomColor
) {
  return (
    <group name="Root_Scene">
      <group name="RootNode">
        <group
          name="CharacterArmature"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <primitive object={nodes.Root} />
        </group>
        <group name="Soldier_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Soldier_Body_1"
            geometry={nodes.Soldier_Body_1.geometry}
            material={materials.Black}
            skeleton={nodes.Soldier_Body_1.skeleton}
          >
            <meshStandardMaterial color={topColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Soldier_Body_2"
            geometry={nodes.Soldier_Body_2.geometry}
            material={materials.Swat}
            skeleton={nodes.Soldier_Body_2.skeleton}
          />
          <skinnedMesh
            name="Soldier_Body_3"
            geometry={nodes.Soldier_Body_3.geometry}
            material={materials.Skin}
            skeleton={nodes.Soldier_Body_3.skeleton}
          />
        </group>
        <group name="Soldier_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Soldier_Feet_1"
            geometry={nodes.Soldier_Feet_1.geometry}
            material={materials.Black}
            skeleton={nodes.Soldier_Feet_1.skeleton}
          />
          <skinnedMesh
            name="Soldier_Feet_2"
            geometry={nodes.Soldier_Feet_2.geometry}
            material={materials.Grey}
            skeleton={nodes.Soldier_Feet_2.skeleton}
          />
        </group>
        <group name="Soldier_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Soldier_Head_1"
            geometry={nodes.Soldier_Head_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Soldier_Head_1.skeleton}
          />
          <skinnedMesh
            name="Soldier_Head_2"
            geometry={nodes.Soldier_Head_2.geometry}
            material={materials.Hair_Brown}
            skeleton={nodes.Soldier_Head_2.skeleton}
          >
            <meshStandardMaterial color={hairColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Soldier_Head_3"
            geometry={nodes.Soldier_Head_3.geometry}
            material={materials.Brown}
            skeleton={nodes.Soldier_Head_3.skeleton}
          />
        </group>
        <group name="Soldier_Legs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Soldier_Legs_1"
            geometry={nodes.Soldier_Legs_1.geometry}
            material={materials.Black}
            skeleton={nodes.Soldier_Legs_1.skeleton}
          />
          <skinnedMesh
            name="Soldier_Legs_2"
            geometry={nodes.Soldier_Legs_2.geometry}
            material={materials.Swat}
            skeleton={nodes.Soldier_Legs_2.skeleton}
          >
            <meshStandardMaterial color={bottomColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Soldier_Legs_3"
            geometry={nodes.Soldier_Legs_3.geometry}
            material={materials.Grey}
            skeleton={nodes.Soldier_Legs_3.skeleton}
          />
        </group>
      </group>
    </group>
  );
}
