/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/MalePunk.glb -o src/components/MalePunk.jsx -r public 
*/

import React from "react";

export function MalePunk(nodes, materials, hairColor, topColor, bottomColor) {
  return (
    <group name="Root_Scene">
      <group name="RootNode">
        <group
          name="CharacterArmature"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <primitive object={nodes.Root} />
        </group>
        <group name="Punk_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Punk_Feet_1"
            geometry={nodes.Punk_Feet_1.geometry}
            material={materials.Black}
            skeleton={nodes.Punk_Feet_1.skeleton}
          />
          <skinnedMesh
            name="Punk_Feet_2"
            geometry={nodes.Punk_Feet_2.geometry}
            material={materials.Skin}
            skeleton={nodes.Punk_Feet_2.skeleton}
          />
        </group>
        <group name="Punk_Legs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Punk_Legs_1"
            geometry={nodes.Punk_Legs_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Punk_Legs_1.skeleton}
          />
          <skinnedMesh
            name="Punk_Legs_2"
            geometry={nodes.Punk_Legs_2.geometry}
            material={materials.LightBlue}
            skeleton={nodes.Punk_Legs_2.skeleton}
          >
            <meshStandardMaterial color={bottomColor} />
          </skinnedMesh>
        </group>
        <group name="Punk_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Punk_Body_1"
            geometry={nodes.Punk_Body_1.geometry}
            material={materials.Black}
            skeleton={nodes.Punk_Body_1.skeleton}
          >
            <meshStandardMaterial color={topColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Punk_Body_2"
            geometry={nodes.Punk_Body_2.geometry}
            material={materials.Skin}
            skeleton={nodes.Punk_Body_2.skeleton}
          />
          <skinnedMesh
            name="Punk_Body_3"
            geometry={nodes.Punk_Body_3.geometry}
            material={materials.White}
            skeleton={nodes.Punk_Body_3.skeleton}
          />
        </group>
        <group name="Punk_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Punk_Head_1"
            geometry={nodes.Punk_Head_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Punk_Head_1.skeleton}
          />
          <skinnedMesh
            name="Punk_Head_2"
            geometry={nodes.Punk_Head_2.geometry}
            material={materials.Red_Dark}
            skeleton={nodes.Punk_Head_2.skeleton}
          >
            <meshStandardMaterial color={hairColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Punk_Head_3"
            geometry={nodes.Punk_Head_3.geometry}
            material={materials.Earrings}
            skeleton={nodes.Punk_Head_3.skeleton}
          />
          <skinnedMesh
            name="Punk_Head_4"
            geometry={nodes.Punk_Head_4.geometry}
            material={materials.Red}
            skeleton={nodes.Punk_Head_4.skeleton}
          >
            <meshStandardMaterial color={hairColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Punk_Head_5"
            geometry={nodes.Punk_Head_5.geometry}
            material={materials.Eyebrows}
            skeleton={nodes.Punk_Head_5.skeleton}
          />
          <skinnedMesh
            name="Punk_Head_6"
            geometry={nodes.Punk_Head_6.geometry}
            material={materials.Eye}
            skeleton={nodes.Punk_Head_6.skeleton}
          />
        </group>
      </group>
    </group>
  );
}
