/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/MaleCasual.glb -o src/components/MaleCasual.jsx -r public 
*/

import React from "react";

export function MaleCasual(nodes, materials, hairColor, topColor, bottomColor) {
  return (
    <group name="Root_Scene">
      <group name="RootNode">
        <group
          name="CharacterArmature"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <primitive object={nodes.Root} />
        </group>
        <group name="Casual2_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Casual2_Feet_1"
            geometry={nodes.Casual2_Feet_1.geometry}
            material={materials.White}
            skeleton={nodes.Casual2_Feet_1.skeleton}
          />
          <skinnedMesh
            name="Casual2_Feet_2"
            geometry={nodes.Casual2_Feet_2.geometry}
            material={materials.Red_Dark}
            skeleton={nodes.Casual2_Feet_2.skeleton}
          />
        </group>
        <group name="Casual2_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Casual2_Body_1"
            geometry={nodes.Casual2_Body_1.geometry}
            material={materials.LightBrown}
            skeleton={nodes.Casual2_Body_1.skeleton}
          >
            <meshStandardMaterial color={topColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Casual2_Body_2"
            geometry={nodes.Casual2_Body_2.geometry}
            material={materials.Skin}
            skeleton={nodes.Casual2_Body_2.skeleton}
          />
        </group>
        <group name="Casual2_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Casual2_Head_1"
            geometry={nodes.Casual2_Head_1.geometry}
            material={materials.Skin}
            skeleton={nodes.Casual2_Head_1.skeleton}
          />
          <skinnedMesh
            name="Casual2_Head_2"
            geometry={nodes.Casual2_Head_2.geometry}
            material={materials.Skin_Darker}
            skeleton={nodes.Casual2_Head_2.skeleton}
          />
          <skinnedMesh
            name="Casual2_Head_3"
            geometry={nodes.Casual2_Head_3.geometry}
            material={materials.Eyebrows}
            skeleton={nodes.Casual2_Head_3.skeleton}
          />
          <skinnedMesh
            name="Casual2_Head_4"
            geometry={nodes.Casual2_Head_4.geometry}
            material={materials.Eye}
            skeleton={nodes.Casual2_Head_4.skeleton}
          />
          <skinnedMesh
            name="Casual2_Head_5"
            geometry={nodes.Casual2_Head_5.geometry}
            material={materials.Hair}
            skeleton={nodes.Casual2_Head_5.skeleton}
          >
            <meshStandardMaterial color={hairColor} />
          </skinnedMesh>
        </group>
        <skinnedMesh
          name="Casual2_Legs"
          geometry={nodes.Casual2_Legs.geometry}
          material={materials.LightBlue}
          skeleton={nodes.Casual2_Legs.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <meshStandardMaterial color={bottomColor} />
        </skinnedMesh>
      </group>
    </group>
  );
}
